sudo: false

branches:
  only:
  - master

language: scala

scala:
- 2.12.8

script:
- sbt ++$TRAVIS_SCALA_VERSION "project site" "run net.wayfarerx.www.site.Website"

jdk:
- oraclejdk8

notifications:
  email:
  - x@wayfarerx.net

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/oversite
  fqdn: wayfarerx.net
  repo: wayfarerx/wayfarerx.github.io
  target-branch: master
  on:
    branch: master